name : Deploy generateData API using node js
on : [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the code
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Downloading the dependencies and starting server
        run: |
          npm ci
          npm run build --if-present
          npm start & npx wait-on http://127.0.0.1:5000
        env:
          CI: true
